name: Publish site

on:
  schedule:
    # Run daily at 14:20 UTC (approx 10:20 America/Toronto during EDT)
    - cron: '20 14 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Generate static site
        run: |
          python NameTrends_autonomous_site_v3/scripts/generate.py
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: NameTrends_autonomous_site_v3/site
          keep_files: true