name: Publish site

on:
  schedule:
    # Run daily at 14:20 UTC (approx 10:20 America/Toronto during EDT)
    - cron: '20 14 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Generate static site
        run: |
      python generate.py
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
publish_dir: site     
keep_files: true
